// Auto-generated by train_readout - DO NOT EDIT
// Training: 875 structures, 875 residues, 1.59% positive

pub const RESERVOIR_DIM: usize = 875;

pub const READOUT_WEIGHTS: &[f32] = &[
     -0.00054273,  -0.08109199,  -0.09403612,  -0.07293213,   0.01708189,   0.02094719,  -0.02715387,   0.20801233, 
      0.06903375,  -0.03046152,  -0.01393573,  -0.07032179, 
];
