// Auto-generated by train_readout - DO NOT EDIT
// Training: 875 structures, 875 residues, 1.59% positive

pub const RESERVOIR_DIM: usize = 875;

pub const READOUT_WEIGHTS: &[f32] = &[
     -0.02470456,  -0.53882045,  -0.01390006,  -0.00673769,  -0.01746961,   0.03553353,   0.61430341,   0.00082249, 
     -0.06463446,  -0.04104187,  -0.02549311,  -0.05404917, 
];
