// Auto-generated by train_readout - DO NOT EDIT
// Training: 875 structures, 875 residues, 1.59% positive

pub const RESERVOIR_DIM: usize = 875;

pub const READOUT_WEIGHTS: &[f32] = &[
      0.15631011,  -0.05195168,  -0.04546450,   0.02633400, 
];
