// Auto-generated by train_readout - DO NOT EDIT
// Training: 875 structures, 875 residues, 1.59% positive

pub const RESERVOIR_DIM: usize = 875;

pub const READOUT_WEIGHTS: &[f32] = &[
     -0.00402876,  -1.09095788,  -0.02872715,  -0.00890916,  -0.01739650,   0.04465165,   1.16489327,   0.00645094, 
     -0.16242473,  -0.06052464,  -0.04224668,  -0.07884705, 
];
