// Auto-generated by train_readout - DO NOT EDIT
// Training: 875 structures, 875 residues, 1.59% positive

pub const RESERVOIR_DIM: usize = 875;

pub const READOUT_WEIGHTS: &[f32] = &[
     -0.05294475,  -0.52762520,  -0.57185292,  -0.47034299,   0.12217902,   0.07723153,  -0.19461678,   1.36319959, 
      0.46341488,  -0.20096949,  -0.09448590,  -0.46950489, 
];
